// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package gorm

// Injectors from wire.go:

func InitializeConnection() (*Connection, error) {
	dataSource := NewDataSource()
	connection, err := NewConnection(dataSource)
	if err != nil {
		return nil, err
	}
	return connection, nil
}

func InitializeDataSource() *DataSource {
	dataSource := NewDataSource()
	return dataSource
}
